### PR TITLE
HMIS-902 configure hmi case hq

### PR DESCRIPTION
**Pull request by chris-pateman**
### Change description ###
Set up hmi case hq

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ X ] No
```

### CODE REVIEW

**Review by timja — COMMENTED** [review]
have you got this working in another env? just that i see 2 envs here, and have been getting quite burnt recently from people 'breaking' the env

**Comment by chris-pateman** [comment]
> 
> 
> have you got this working in another env? just that i see 2 envs here, and have been getting quite burnt recently from people 'breaking' the en

@timja I have not. I can reduce this down to use dev, so we can test a PR and make sure that is working before progressing to staging.

**Comment by chris-pateman** [comment]
@timja I have left it only in the dev flux patch so it should only be used in the PR now

**Review by timja — CHANGES_REQUESTED** [review]
you're missing hmi in https://github.com/hmcts/shared-services-flux/blob/master/k8s/environments/dev/common-overlay/kustomization.yaml

**Comment by chris-pateman** [comment]
@timja good spot and added now

**Review by timja — APPROVED** [review]

**Pull request merged**
